// ...existing code...
// CatalogFeature now owns the catalog screen implementation and previews.
// This file is intentionally left as a placeholder so the app target no longer defines the feature view.
