// ...existing code...
// CatalogFeature now owns the catalog item model, repository abstraction, and mock.
// This file is intentionally left as a placeholder so the app target no longer defines those types.
